### ISSUE TITLE
implicit declaration of function '_frxt_setup_switch' when build with ESP-IDFv4.4

### ISSUE THREAD

**Issue by ksh1ng** [jeremyjh/ESP32_TFT_library#26]
>idf.py build
...
[1011/1050] Building C object esp-idf/spiffs/CMakeFiles/__idf_spiffs.dir/mutex.c.obj
FAILED: esp-idf/spiffs/CMakeFiles/__idf_spiffs.dir/mutex.c.obj
ccache C:\Espressif\tools\xtensa-esp32-elf\esp-2021r2-patch3-8.4.0\xtensa-esp32-elf\bin\xtensa-esp32-elf-gcc.exe  -Iconfig -I../components/spiffs -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/newlib/platform_include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/freertos/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/esp_additions/freertos -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/freertos/port/xtensa/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/esp_additions -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_hw_support/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_hw_support/include/soc -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_hw_support/include/soc/esp32 -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_hw_support/port/esp32/. -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_hw_support/port/esp32/private_include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/heap/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/log/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/lwip/include/apps -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/lwip/include/apps/sntp -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/lwip/lwip/src/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/lwip/port/esp32/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/lwip/port/esp32/include/arch -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/soc/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/soc/esp32/. -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/soc/esp32/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/hal/esp32/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/hal/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/hal/platform_port/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_rom/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_rom/include/esp32 -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_rom/esp32 -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_common/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_system/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_system/port/soc -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_system/port/public_compat -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp32/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/xtensa/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/xtensa/esp32/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/driver/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/driver/esp32/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_pm/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_ringbuf/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/efuse/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/efuse/esp32/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/vfs/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_wifi/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_event/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_netif/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_eth/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/tcpip_adapter/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_phy/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_phy/esp32/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_ipc/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/app_trace/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_timer/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/spi_flash/include -mlongcalls -Wno-frame-address -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -ggdb -Og -fmacro-prefix-map=C:/Users/kshsu/Documents/ESP32/IOT_Practice/tft_lib/ESP32_TFT_library=. -fmacro-prefix-map=C:/Espressif/frameworks/esp-idf-v4.4.1=IDF -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -fno-jump-tables -fno-tree-switch-conversion -std=gnu99 -Wno-old-style-declaration -D_GNU_SOURCE -DIDF_VER=\"v4.4.1\" -DESP_PLATFORM -D_POSIX_READER_WRITER_LOCKS -MD -MT esp-idf/spiffs/CMakeFiles/__idf_spiffs.dir/mutex.c.obj -MF esp-idf\spiffs\CMakeFiles\__idf_spiffs.dir\mutex.c.obj.d -o esp-idf/spiffs/CMakeFiles/__idf_spiffs.dir/mutex.c.obj -c ../components/spiffs/mutex.c
../components/spiffs/mutex.c: In function 'mtx_init':
../components/spiffs/mutex.c:40:2: error: implicit declaration of function '_frxt_setup_switch' [-Werror=implicit-function-declaration]
  _frxt_setup_switch(); \
  ^~~~~~~~~~~~~~~~~~
../components/spiffs/mutex.c:55:13: note: in expansion of macro 'portEND_SWITCHING_ISR'
             portEND_SWITCHING_ISR( xHigherPriorityTaskWoken );
             ^~~~~~~~~~~~~~~~~~~~~
cc1.exe: some warnings being treated as errors
[1020/1050] Building C object esp-idf/wifi_provisioning/CMakeFiles/__idf_wifi_provisioning.dir/src/wifi_scan.c.obj
ninja: build stopped: subcommand failed.
ninja failed with exit code 1

C:\Users\kshsu\Documents\ESP32\IOT_Practice\tft_lib\ESP32_TFT_library>idf.py build
Executing action: all (aliases: build)
Running ninja in directory c:\users\kshsu\documents\esp32\iot_practice\tft_lib\esp32_tft_library\build
Executing "ninja all"...
[0/1] Re-running CMake...
-- ccache will be used for faster recompilation
-- Building ESP-IDF components for target esp32
-- Project sdkconfig file C:/Users/kshsu/Documents/ESP32/IOT_Practice/tft_lib/ESP32_TFT_library/sdkconfig
warning: the int symbol SPIFFS_BASE_ADDR (defined at C:/Users/kshsu/Documents/ESP32/IOT_Practice/tft_lib/ESP32_TFT_library/components/spiffs/Kconfig:3) has a non-int default 0x180000 (undefined)
Loading defaults file C:/Users/kshsu/Documents/ESP32/IOT_Practice/tft_lib/ESP32_TFT_library/sdkconfig.defaults...
C:/Users/kshsu/Documents/ESP32/IOT_Practice/tft_lib/ESP32_TFT_library/sdkconfig.defaults:6 CONFIG_ESP32_PANIC_PRINT_HALT was replaced with CONFIG_ESP_SYSTEM_PANIC_PRINT_HALT
C:/Users/kshsu/Documents/ESP32/IOT_Practice/tft_lib/ESP32_TFT_library/sdkconfig.defaults:9 CONFIG_MAIN_TASK_STACK_SIZE was replaced with CONFIG_ESP_MAIN_TASK_STACK_SIZE
C:/Users/kshsu/Documents/ESP32/IOT_Practice/tft_lib/ESP32_TFT_library/sdkconfig.defaults:10 CONFIG_TASK_WDT_TIMEOUT_S was replaced with CONFIG_ESP_TASK_WDT_TIMEOUT_S
-- App "tft_demo" version: 9283df8-dirty
-- Adding linker script C:/Users/kshsu/Documents/ESP32/IOT_Practice/tft_lib/ESP32_TFT_library/build/esp-idf/esp_system/ld/memory.ld
-- Adding linker script C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_system/ld/esp32/sections.ld.in
-- Adding linker script C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_rom/esp32/ld/esp32.rom.ld
-- Adding linker script C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_rom/esp32/ld/esp32.rom.api.ld
-- Adding linker script C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_rom/esp32/ld/esp32.rom.libgcc.ld
-- Adding linker script C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_rom/esp32/ld/esp32.rom.newlib-data.ld
-- Adding linker script C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_rom/esp32/ld/esp32.rom.syscalls.ld
-- Adding linker script C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_rom/esp32/ld/esp32.rom.newlib-funcs.ld
-- Adding linker script C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_rom/esp32/ld/esp32.rom.newlib-time.ld
-- Adding linker script C:/Espressif/frameworks/esp-idf-v4.4.1/components/soc/esp32/ld/esp32.peripherals.ld
-- Components: app_trace app_update asio bootloader bootloader_support bt cbor cmock coap console cxx driver efuse esp-tls esp32 esp_adc_cal esp_common esp_eth esp_event esp_gdbstub esp_hid esp_http_client esp_http_server esp_https_ota esp_https_server esp_hw_support esp_ipc esp_lcd esp_local_ctrl esp_netif esp_phy esp_pm esp_ringbuf esp_rom esp_serial_slave_link esp_system esp_timer esp_websocket_client esp_wifi espcoredump esptool_py expat fatfs freemodbus freertos hal heap idf_test ieee802154 jsmn json libsodium log lwip main mbedtls mdns mkspiffs mqtt newlib nghttp nvs_flash openssl openthread partition_table perfmon protobuf-c protocomm pthread sdmmc soc spi_flash spidriver spiffs spiffs_image tcp_transport tcpip_adapter tft tinyusb ulp unity usb vfs wear_levelling wifi_provisioning wpa_supplicant xtensa
-- Component paths: C:/Espressif/frameworks/esp-idf-v4.4.1/components/app_trace C:/Espressif/frameworks/esp-idf-v4.4.1/components/app_update C:/Espressif/frameworks/esp-idf-v4.4.1/components/asio C:/Espressif/frameworks/esp-idf-v4.4.1/components/bootloader C:/Espressif/frameworks/esp-idf-v4.4.1/components/bootloader_support C:/Espressif/frameworks/esp-idf-v4.4.1/components/bt C:/Espressif/frameworks/esp-idf-v4.4.1/components/cbor C:/Espressif/frameworks/esp-idf-v4.4.1/components/cmock C:/Espressif/frameworks/esp-idf-v4.4.1/components/coap C:/Espressif/frameworks/esp-idf-v4.4.1/components/console C:/Espressif/frameworks/esp-idf-v4.4.1/components/cxx C:/Espressif/frameworks/esp-idf-v4.4.1/components/driver C:/Espressif/frameworks/esp-idf-v4.4.1/components/efuse C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp-tls C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp32 C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_adc_cal C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_common C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_eth C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_event C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_gdbstub C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_hid C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_http_client C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_http_server C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_https_ota C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_https_server C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_hw_support C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_ipc C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_lcd C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_local_ctrl C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_netif C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_phy C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_pm C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_ringbuf C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_rom C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_serial_slave_link C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_system C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_timer C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_websocket_client C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_wifi C:/Espressif/frameworks/esp-idf-v4.4.1/components/espcoredump C:/Espressif/frameworks/esp-idf-v4.4.1/components/esptool_py C:/Espressif/frameworks/esp-idf-v4.4.1/components/expat C:/Espressif/frameworks/esp-idf-v4.4.1/components/fatfs C:/Espressif/frameworks/esp-idf-v4.4.1/components/freemodbus C:/Espressif/frameworks/esp-idf-v4.4.1/components/freertos C:/Espressif/frameworks/esp-idf-v4.4.1/components/hal C:/Espressif/frameworks/esp-idf-v4.4.1/components/heap C:/Espressif/frameworks/esp-idf-v4.4.1/components/idf_test C:/Espressif/frameworks/esp-idf-v4.4.1/components/ieee802154 C:/Espressif/frameworks/esp-idf-v4.4.1/components/jsmn C:/Espressif/frameworks/esp-idf-v4.4.1/components/json C:/Espressif/frameworks/esp-idf-v4.4.1/components/libsodium C:/Espressif/frameworks/esp-idf-v4.4.1/components/log C:/Espressif/frameworks/esp-idf-v4.4.1/components/lwip C:/Users/kshsu/Documents/ESP32/IOT_Practice/tft_lib/ESP32_TFT_library/main C:/Espressif/frameworks/esp-idf-v4.4.1/components/mbedtls C:/Espressif/frameworks/esp-idf-v4.4.1/components/mdns C:/Users/kshsu/Documents/ESP32/IOT_Practice/tft_lib/ESP32_TFT_library/components/mkspiffs C:/Espressif/frameworks/esp-idf-v4.4.1/components/mqtt C:/Espressif/frameworks/esp-idf-v4.4.1/components/newlib C:/Espressif/frameworks/esp-idf-v4.4.1/components/nghttp C:/Espressif/frameworks/esp-idf-v4.4.1/components/nvs_flash C:/Espressif/frameworks/esp-idf-v4.4.1/components/openssl C:/Espressif/frameworks/esp-idf-v4.4.1/components/openthread C:/Espressif/frameworks/esp-idf-v4.4.1/components/partition_table C:/Espressif/frameworks/esp-idf-v4.4.1/components/perfmon C:/Espressif/frameworks/esp-idf-v4.4.1/components/protobuf-c C:/Espressif/frameworks/esp-idf-v4.4.1/components/protocomm C:/Espressif/frameworks/esp-idf-v4.4.1/components/pthread C:/Espressif/frameworks/esp-idf-v4.4.1/components/sdmmc C:/Espressif/frameworks/esp-idf-v4.4.1/components/soc C:/Espressif/frameworks/esp-idf-v4.4.1/components/spi_flash C:/Users/kshsu/Documents/ESP32/IOT_Practice/tft_lib/ESP32_TFT_library/components/spidriver C:/Users/kshsu/Documents/ESP32/IOT_Practice/tft_lib/ESP32_TFT_library/components/spiffs C:/Users/kshsu/Documents/ESP32/IOT_Practice/tft_lib/ESP32_TFT_library/components/spiffs_image C:/Espressif/frameworks/esp-idf-v4.4.1/components/tcp_transport C:/Espressif/frameworks/esp-idf-v4.4.1/components/tcpip_adapter C:/Users/kshsu/Documents/ESP32/IOT_Practice/tft_lib/ESP32_TFT_library/components/tft C:/Espressif/frameworks/esp-idf-v4.4.1/components/tinyusb C:/Espressif/frameworks/esp-idf-v4.4.1/components/ulp C:/Espressif/frameworks/esp-idf-v4.4.1/components/unity C:/Espressif/frameworks/esp-idf-v4.4.1/components/usb C:/Espressif/frameworks/esp-idf-v4.4.1/components/vfs C:/Espressif/frameworks/esp-idf-v4.4.1/components/wear_levelling C:/Espressif/frameworks/esp-idf-v4.4.1/components/wifi_provisioning C:/Espressif/frameworks/esp-idf-v4.4.1/components/wpa_supplicant C:/Espressif/frameworks/esp-idf-v4.4.1/components/xtensa
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/kshsu/Documents/ESP32/IOT_Practice/tft_lib/ESP32_TFT_library/build
[1/36] Performing build step for 'bootloader'
[1/1] cmd.exe /C "cd /D C:\Users\kshsu\Documents\ESP32\IOT_Practice\tft_lib\ESP32_TFT_library\build\bootloader\esp-idf\esptool_py && C:\Espressif\python_env\idf4.4_py3.8_env\Scripts\python.exe C:/Espressif/frameworks/esp-idf-v4.4.1/components/partition_table/check_sizes.py --offset 0x8000 bootloader 0x1000 C:/Users/kshsu/Documents/ESP32/IOT_Practice/tft_lib/ESP32_TFT_library/build/bootloader/bootloader.bin"
Bootloader binary size 0x62c0 bytes. 0xd40 bytes (12%) free.
[5/34] Building C object esp-idf/spiffs/CMakeFiles/__idf_spiffs.dir/mutex.c.obj
FAILED: esp-idf/spiffs/CMakeFiles/__idf_spiffs.dir/mutex.c.obj
ccache C:\Espressif\tools\xtensa-esp32-elf\esp-2021r2-patch3-8.4.0\xtensa-esp32-elf\bin\xtensa-esp32-elf-gcc.exe  -Iconfig -I../components/spiffs -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/newlib/platform_include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/freertos/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/esp_additions/freertos -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/freertos/port/xtensa/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/esp_additions -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_hw_support/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_hw_support/include/soc -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_hw_support/include/soc/esp32 -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_hw_support/port/esp32/. -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_hw_support/port/esp32/private_include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/heap/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/log/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/lwip/include/apps -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/lwip/include/apps/sntp -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/lwip/lwip/src/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/lwip/port/esp32/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/lwip/port/esp32/include/arch -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/soc/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/soc/esp32/. -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/soc/esp32/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/hal/esp32/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/hal/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/hal/platform_port/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_rom/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_rom/include/esp32 -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_rom/esp32 -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_common/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_system/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_system/port/soc -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_system/port/public_compat -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp32/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/xtensa/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/xtensa/esp32/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/driver/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/driver/esp32/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_pm/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_ringbuf/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/efuse/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/efuse/esp32/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/vfs/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_wifi/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_event/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_netif/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_eth/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/tcpip_adapter/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_phy/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_phy/esp32/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_ipc/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/app_trace/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_timer/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/spi_flash/include -mlongcalls -Wno-frame-address -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -ggdb -Og -fmacro-prefix-map=C:/Users/kshsu/Documents/ESP32/IOT_Practice/tft_lib/ESP32_TFT_library=. -fmacro-prefix-map=C:/Espressif/frameworks/esp-idf-v4.4.1=IDF -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -fno-jump-tables -fno-tree-switch-conversion -std=gnu99 -Wno-old-style-declaration -D_GNU_SOURCE -DIDF_VER=\"v4.4.1\" -DESP_PLATFORM -D_POSIX_READER_WRITER_LOCKS -MD -MT esp-idf/spiffs/CMakeFiles/__idf_spiffs.dir/mutex.c.obj -MF esp-idf\spiffs\CMakeFiles\__idf_spiffs.dir\mutex.c.obj.d -o esp-idf/spiffs/CMakeFiles/__idf_spiffs.dir/mutex.c.obj -c ../components/spiffs/mutex.c
../components/spiffs/mutex.c: In function 'mtx_init':
../components/spiffs/mutex.c:40:2: error: implicit declaration of function '_frxt_setup_switch' [-Werror=implicit-function-declaration]
  _frxt_setup_switch(); \
  ^~~~~~~~~~~~~~~~~~
../components/spiffs/mutex.c:55:13: note: in expansion of macro 'portEND_SWITCHING_ISR'
             portEND_SWITCHING_ISR( xHigherPriorityTaskWoken );
             ^~~~~~~~~~~~~~~~~~~~~
cc1.exe: some warnings being treated as errors
[14/34] Building C object esp-idf/wifi_provisioning/CMakeFiles/__idf_wifi_provisioning.dir/src/manager.c.obj
ninja: build stopped: subcommand failed.
ninja failed with exit code 1

Not sure if _frxt_setup_switch() is deprecated...

**Comment by ksh1ng** [comment]
It can be solved by add "extern void _frxt_setup_switch( void );" before _frxt_setup_switch() called.
